### ISSUE TITLE
有料プランの引き落とし明細に「Doorkeeper」とわかるように書いてほしい

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#42]
現状は「オンライン決済」になっている

**Comment by pwim** [comment]
まだ明細に「オンライン決済」を表示しますか？Stripeによると、最初は「オンライン決済」を表示する可能性があるけど、数時間後、DOORKEEPER、ドアキーパーなど表示します。詳しくは、以下にStripeの返事があります。英語ですけど。

---

This is an unfortunate limitation of Japan's domestic credit card authorisation switching networks.

When a payment happens, an "authorisation" is first sent to the customer's credit card company to hold the funds. These funds are then "settled" in daily batches. In most countries, the authorisation message contains statement descriptor fields, but the domestic networks do not contain these fields. Rather, the daily settlement data files contain the statement descriptors.

This means that the credit card companies don't know what to display for the first 0-24 hours, until the settlement data arrives. Japanese credit card companies generally don't display anything until the settlement data arrives because of this limitation, but there are some exceptions:
- When you authorise against a debit card, the funds in the bank account are immediately withheld, so the card company shows whatever information they have available.
- Foreign cards expect statement descriptors in authorisation messages so display whatever information they have available.
- SMCC's Vpass online statement can show charges before they are settled.
- Some fraud-prevention systems (such as one used by Rakuten Card) will email cardholders when a suspicious authorisation occurs, and this will include whatever information they have available.

I hope this makes sense, and sorry that one of these edge cases confused a customer of yours. Please let me know if you suspect that this is an issue for customers outside of any of the above cases.

**Comment by kdmsnr** [comment]
ずっと「オンライン決済」のままです。

**Comment by pwim** [comment]
残念ですが、クレジットカードによると、「オンライン決済」をずっと表示する可能性があります。

**Comment by kdmsnr** [comment]
:-(
